#include "riscv.h"

namespace orfos::kernel::arch {
#define ORFOS_KERNEL_ARCH_DEFINE_REGISTER(name) Register_##name name

  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(mhartid);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(mstatus);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(mepc);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(mie);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(medeleg);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(mideleg);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(mtvec);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(mscratch);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(mcounteren);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(time);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(pmpcfg0);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(pmpaddr0);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(sstatus);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(sip);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(sie);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(sepc);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(stvec);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(satp);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(scause);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(stval);

  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(sp);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(tp);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(ra);

  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(sfence_vma);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(mret);
  ORFOS_KERNEL_ARCH_DEFINE_REGISTER(wfi);
} // namespace orfos::kernel::arch