#ifndef ORFOS_KERNEL_SYSCALL_SYSCALL_KEY_H_
#define ORFOS_KERNEL_SYSCALL_SYSCALL_KEY_H_

#define SYS_FORK 1
#define SYS_EXIT 2
#define SYS_READ 5
#define SYS_EXEC 7
#define SYS_OPEN 15
#define SYS_WRITE 16
#define SYS_MKNOD 17
#define SYS_CLOSE 21

#endif // ORFOS_KERNEL_SYSCALL_SYSCALL_KEY_H_